Attribute VB_Name = "Module1"
Global db As Database
Global Vn As Recordset
Global Ctm As Recordset
Global Itm As Recordset
Global Tin As Recordset
Global Sal As Recordset
Global Vst As Recordset
Global Vnd As Recordset
